name: Build JVM/JS/iOS/macOS/tvOS/MinGW/wasmJS/wasmWasi/Linux
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: kmmresult
          path: |
            build/libs/*jar
